# run: conda env create --file environment.yml
name: base
channels:
    - conda-forge
    - anaconda
    - defaults
dependencies:
    # Runtime
    - fbprophet
    - matplotlib
    - numpy
    - optuna
    - pandas
    - pandas-profiling
    - plotly
    - python-dateutil>=2.8.0
    - python>=3.7
    - requests
    - scikit-learn
    - scikit-optimize
    - scipy
    - seaborn
    - sqlite
    - statsmodels
